package com.arodriverkotlin.order

enum class TransportState {
    OFFERED, ACCEPTED, ARRIVING, ON_BOARD, EN_ROUTE,
    DROPPED_OFF, COMPLETED, CANCELLED, EXPIRED
}

enum class FoodState {
    OFFERED, ACCEPTED, ARRIVING, WAITING_FOOD, PICKED_UP,
    EN_ROUTE, DELIVERED, COMPLETED, CANCELLED, EXPIRED
}

enum class ExpressState {
    OFFERED, ACCEPTED, AT_WAREHOUSE, PICKED_UP, EN_ROUTE,
    DELIVERED, COMPLETED, CANCELLED, EXPIRED
}

enum class SendState {
    OFFERED, ACCEPTED, AT_PICKUP, PICKED_UP, EN_ROUTE,
    DELIVERED, COMPLETED, CANCELLED, EXPIRED
}

enum class ShopState {
    OFFERED, ACCEPTED, AT_MERCHANT, SHOPPING, PICKED_UP,
    EN_ROUTE, DELIVERED, COMPLETED, CANCELLED, EXPIRED
}
