/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        background: '#0A0A0A',
        card: '#262626',
        textPrimary: '#FAFAFA',
        textSecondary: '#A3A3A3',
        "on-tertiary-fixed": "#483d00",
        "surface-dim": "#0e0e0e",
        "surface-container-highest": "#262626",
        "secondary-dim": "#ddda49",
        "tertiary-fixed": "#fce047",
        "primary-dim": "#beee00",
        "secondary-fixed": "#ece856",
        "secondary-fixed-dim": "#ddda49",
        "inverse-primary": "#516700",
        "surface": "#0e0e0e",
        "on-tertiary-container": "#5d5000",
        "primary-container": "#cafd00",
        "error": "#ff7351",
        "error-container": "#b92902",
        "on-primary": "#516700",
        "on-tertiary-fixed-variant": "#685900",
        "on-secondary-fixed-variant": "#605e00",
        "on-secondary-container": "#fffca4",
        "inverse-on-surface": "#565554",
        "tertiary": "#ffeea5",
        "outline": "#777575",
        "outline-variant": "#494847",
        "primary-fixed-dim": "#beee00",
        "error-dim": "#d53d18",
        "on-secondary-fixed": "#434100",
        "surface-container": "#1a1919",
        "primary": "#f3ffca",
        "secondary-container": "#636100",
        "on-surface": "#ffffff",
        "surface-container-low": "#131313",
        "surface-bright": "#2c2c2c",
        "on-surface-variant": "#adaaaa",
        "surface-container-high": "#201f1f",
        "surface-container-lowest": "#000000",
        "on-primary-fixed": "#3a4a00",
        "tertiary-fixed-dim": "#edd13a",
        "surface-variant": "#262626",
        "on-primary-fixed-variant": "#526900",
        "tertiary-container": "#fce047",
        "tertiary-dim": "#edd13a",
        "on-error": "#450900",
        "on-error-container": "#ffd2c8",
        "on-tertiary": "#665800",
        "inverse-surface": "#fcf8f8",
        "on-secondary": "#565400",
        "on-primary-container": "#4a5e00",
        "secondary": "#ece856",
        "primary-fixed": "#cafd00",
        "surface-tint": "#f3ffca",
        "on-background": "#ffffff"
      },
      fontFamily: {
        sans: ['Inter', 'Outfit', 'sans-serif'],
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
