name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build User App
        run: |
          cd aro-drive-vite
          npm install
          npm run build

      - name: Build Driver App
        run: |
          cd aro-drive-driver-vite
          npm install
          npm run build

      - name: Build Admin App
        run: |
          cd aro-admin-vite
          npm install
          npm run build

      - name: Install Functions Deps
        run: |
          cd functions
          npm install

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,functions --project gb-delivery-41bf6
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
